### ISSUE TITLE
documentation broken links

### ISSUE THREAD

**Issue by sonalgoyal** [zinggAI/zingg#57] opened 2021-11-30 06:40 UTC
https://docs.zingg.ai/docs/setup/configuration.html - pipes links are broken

**Comment by sonalgoyal** [comment] 2021-12-02 12:33
broken: https://docs.zingg.ai/docs/faq.html#how-much-training-is-enough hardware sizing

**Comment by sonalgoyal** [comment] 2021-12-02 12:33
https://docs.zingg.ai/docs/pretrainedModels.html

**Comment by navinrathore** [comment] 2021-12-03 12:53
Duplicate of #59

**Closed** 2021-12-06 04:26 UTC
