### ISSUE TITLE
zingg0.4.0 Exporting Labeled Data throws error

### ISSUE THREAD

**Issue by fdletter1980** [zinggAI/zingg#775] opened 2024-02-01 20:13 UTC
**Describe the bug**
Running the --phase exportModel command with usual command structure like the other phases (which all work) throws an error.

**To Reproduce**
1. After running both findTrainingData and label phase successfully (along with GenerateDocs, Train and Match) the --phase ExportModel throws an error.
2. Exact command structure used (that works with any other phase:):
zingg.sh --properties-file /zingg-0.4.0/models/er-agent/zingg.conf --phase exportModel --conf /zingg-0.4.0/models/er-agent/findTrainingData.json --location /zingg-0.4.0/models/er-agent

**Expected behavior**
Expected the labelled training data to be saved in a .csv in the location provided.

**Screenshots**
![Export Training Data](https://github.com/zinggAI/zingg/assets/83425433/ed2fba36-a6bc-4c1b-a45b-567bfeaf9848)

**Desktop (please complete the following information):**
- Running docker container 0.4.0 on GCP

**Additional context**

**Comment by gnanaprakash-ravi** [comment] 2024-02-02 09:06
exportModel, as a Python phase, the logs in the Python code do not get printed,

command mentioned in the docs: 
`./scripts/zingg.sh --phase exportModel --conf <path to conf> --location <folder to save the csv>`

giving NullPointerException error
@sonalgoyal

**Comment by vikasgupta78** [comment] 2024-04-24 08:41
duplicate of https://github.com/zinggAI/zingg/issues/817

**Closed by vikasgupta78** 2024-04-24 08:41 UTC
